### ISSUE TITLE
MathJax CDN shutted down

### ISSUE THREAD

**Issue by flinhong** [hexojs/hexo-math#41]
It's said:

> The MathJax CDN hosted at cdn.mathjax.org will be shutting down on April 30, 2017. 
> Current and future releases available on other CDN providers.

from [https://www.mathjax.org/cdn-shutting-down/](https://www.mathjax.org/cdn-shutting-down/)

It's better to update to a CDN lib, e.g. https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?...

**Comment by AlphaMistral** [comment]
Besides, the cdn currently in use is in http which may fail when the host server uses https(For example, GitHub Page). Hence I strongly recommend updating the CDN. I have created a pull request which only changes the cdn link but the Travis build fails. I hope the repo owner could have a look at this. 
Anyway, if you are suffering from being incapable of using MathJax on your https server, you may manually change the cdn link by attaching "https:" in front of the original one by altering options.es6, options.js and mathjax.html. GL&HF!

**Comment by ChenPt** [comment]
@AlphaMistral thanks to your suggession.  Because Netlify use https,  i can't use mathjax in my blog. I can use mathjax after i uppdate the mathjax CDN.  I use this CDN `https://cdn.staticfile.org/MathJax/MathJax-2.6-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML` 

对于使用HTTPS站点的静态托管商来说，最好更新mathjax的CDN提供商. 我是用的国内的CDN，而且还得是使用了HTTPs的CDN地址.
